import dotenv from 'dotenv';
import { connectDB } from '../config/db';
import { Menu } from '../models/Menu.model';

dotenv.config();

const menuItems = {
  main: [
    {
      name: 'Butter Chicken',
      description: 'Creamy tomato-based curry with tender chicken pieces, cooked in butter and aromatic spices. Served with basmati rice and naan.',
      price: 350,
      category: 'main',
      isVeg: false,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Chicken', 'Tomato', 'Butter', 'Cream', 'Spices', 'Onion', 'Garlic'],
      preparationTime: 25,
      addOns: [
        { name: 'Extra Butter', price: 30, available: true },
        { name: 'Extra Naan', price: 40, available: true },
        { name: 'Extra Rice', price: 25, available: true },
      ],
    },
    {
      name: 'Paneer Butter Masala',
      description: 'Rich and creamy curry with soft paneer cubes in a tomato-based gravy, flavored with butter and spices. A vegetarian favorite.',
      price: 320,
      category: 'main',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Paneer', 'Tomato', 'Butter', 'Cream', 'Spices', 'Onion'],
      preparationTime: 20,
      addOns: [
        { name: 'Extra Paneer', price: 60, available: true },
        { name: 'Extra Naan', price: 40, available: true },
        { name: 'Extra Rice', price: 25, available: true },
      ],
    },
    {
      name: 'Chicken Biryani',
      description: 'Fragrant basmati rice cooked with tender chicken pieces, aromatic spices, and herbs. Served with raita and pickle.',
      price: 380,
      category: 'main',
      isVeg: false,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Basmati Rice', 'Chicken', 'Spices', 'Onion', 'Yogurt', 'Mint', 'Coriander'],
      preparationTime: 30,
      addOns: [
        { name: 'Extra Chicken', price: 80, available: true },
        { name: 'Extra Raita', price: 30, available: true },
        { name: 'Extra Pickle', price: 20, available: true },
      ],
    },
    {
      name: 'Veg Biryani',
      description: 'Aromatic basmati rice cooked with mixed vegetables, spices, and herbs. A flavorful vegetarian delight served with raita.',
      price: 280,
      category: 'main',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Basmati Rice', 'Mixed Vegetables', 'Spices', 'Onion', 'Yogurt', 'Mint'],
      preparationTime: 25,
      addOns: [
        { name: 'Extra Vegetables', price: 50, available: true },
        { name: 'Extra Raita', price: 30, available: true },
        { name: 'Extra Pickle', price: 20, available: true },
      ],
    },
    {
      name: 'Dal Makhani',
      description: 'Creamy black lentils cooked overnight with butter and cream, slow-cooked to perfection. A rich and comforting dish.',
      price: 250,
      category: 'main',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Black Lentils', 'Kidney Beans', 'Butter', 'Cream', 'Tomato', 'Spices'],
      preparationTime: 20,
      addOns: [
        { name: 'Extra Butter', price: 30, available: true },
        { name: 'Extra Naan', price: 40, available: true },
        { name: 'Extra Rice', price: 25, available: true },
      ],
    },
    {
      name: 'Chicken Tikka Masala',
      description: 'Tender grilled chicken tikka pieces in a rich, creamy tomato-based curry. A popular Indo-British fusion dish.',
      price: 360,
      category: 'main',
      isVeg: false,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Chicken Tikka', 'Tomato', 'Cream', 'Spices', 'Onion', 'Garlic'],
      preparationTime: 25,
      addOns: [
        { name: 'Extra Chicken', price: 80, available: true },
        { name: 'Extra Naan', price: 40, available: true },
        { name: 'Extra Rice', price: 25, available: true },
      ],
    },
    {
      name: 'Palak Paneer',
      description: 'Fresh spinach curry with soft paneer cubes, cooked with aromatic spices. A healthy and delicious vegetarian option.',
      price: 290,
      category: 'main',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Spinach', 'Paneer', 'Onion', 'Tomato', 'Spices', 'Garlic', 'Ginger'],
      preparationTime: 20,
      addOns: [
        { name: 'Extra Paneer', price: 60, available: true },
        { name: 'Extra Naan', price: 40, available: true },
        { name: 'Extra Rice', price: 25, available: true },
      ],
    },
    {
      name: 'Lamb Rogan Josh',
      description: 'Tender lamb pieces cooked in a rich, aromatic curry with yogurt and spices. A classic Kashmiri delicacy.',
      price: 420,
      category: 'main',
      isVeg: false,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Lamb', 'Yogurt', 'Onion', 'Spices', 'Ginger', 'Garlic', 'Tomato'],
      preparationTime: 35,
      addOns: [
        { name: 'Extra Lamb', price: 100, available: true },
        { name: 'Extra Naan', price: 40, available: true },
        { name: 'Extra Rice', price: 25, available: true },
      ],
    },
    {
      name: 'Chana Masala',
      description: 'Spiced chickpeas cooked in a tangy tomato-based curry with aromatic spices. A protein-rich vegetarian favorite.',
      price: 240,
      category: 'main',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Chickpeas', 'Tomato', 'Onion', 'Spices', 'Ginger', 'Garlic'],
      preparationTime: 18,
      addOns: [
        { name: 'Extra Chana', price: 40, available: true },
        { name: 'Extra Naan', price: 40, available: true },
        { name: 'Extra Rice', price: 25, available: true },
      ],
    },
    {
      name: 'Fish Curry',
      description: 'Fresh fish cooked in a tangy and spicy coconut-based curry with aromatic spices. A coastal delicacy.',
      price: 380,
      category: 'main',
      isVeg: false,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Fish', 'Coconut', 'Tomato', 'Spices', 'Onion', 'Curry Leaves'],
      preparationTime: 25,
      addOns: [
        { name: 'Extra Fish', price: 90, available: true },
        { name: 'Extra Rice', price: 25, available: true },
        { name: 'Extra Curry', price: 30, available: true },
      ],
    },
  ],
  dessert: [
    {
      name: 'Gulab Jamun',
      description: 'Soft, spongy milk dumplings soaked in sweet rose-flavored syrup. A classic Indian dessert served warm.',
      price: 120,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Milk Powder', 'Flour', 'Sugar', 'Rose Water', 'Cardamom'],
      preparationTime: 15,
      addOns: [
        { name: 'Extra Gulab Jamun (2 pcs)', price: 60, available: true },
        { name: 'Ice Cream', price: 50, available: true },
        { name: 'Extra Syrup', price: 20, available: true },
      ],
    },
    {
      name: 'Rasmalai',
      description: 'Soft cottage cheese dumplings soaked in sweetened, cardamom-flavored milk. A refreshing and creamy dessert.',
      price: 140,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Cottage Cheese', 'Milk', 'Sugar', 'Cardamom', 'Saffron', 'Pistachios'],
      preparationTime: 20,
      addOns: [
        { name: 'Extra Rasmalai (2 pcs)', price: 70, available: true },
        { name: 'Extra Nuts', price: 30, available: true },
        { name: 'Extra Saffron', price: 40, available: true },
      ],
    },
    {
      name: 'Kheer',
      description: 'Creamy rice pudding cooked with milk, sugar, and cardamom, garnished with nuts and saffron.',
      price: 130,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Rice', 'Milk', 'Sugar', 'Cardamom', 'Almonds', 'Raisins', 'Saffron'],
      preparationTime: 25,
      addOns: [
        { name: 'Extra Nuts', price: 30, available: true },
        { name: 'Extra Saffron', price: 40, available: true },
        { name: 'Extra Serving', price: 60, available: true },
      ],
    },
    {
      name: 'Gajar Ka Halwa',
      description: 'Sweet carrot pudding cooked with milk, ghee, and sugar, garnished with nuts. A winter favorite.',
      price: 150,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Carrots', 'Milk', 'Ghee', 'Sugar', 'Cardamom', 'Almonds', 'Raisins'],
      preparationTime: 30,
      addOns: [
        { name: 'Extra Nuts', price: 30, available: true },
        { name: 'Extra Ghee', price: 25, available: true },
        { name: 'Ice Cream', price: 50, available: true },
      ],
    },
    {
      name: 'Jalebi',
      description: 'Crispy, spiral-shaped sweet treats soaked in sugar syrup. Served hot and crispy.',
      price: 110,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Flour', 'Yogurt', 'Sugar', 'Saffron', 'Cardamom'],
      preparationTime: 15,
      addOns: [
        { name: 'Extra Jalebi (5 pcs)', price: 50, available: true },
        { name: 'Rabri', price: 60, available: true },
        { name: 'Extra Syrup', price: 20, available: true },
      ],
    },
    {
      name: 'Rasgulla',
      description: 'Soft, spongy cottage cheese balls soaked in light sugar syrup. A refreshing Bengali dessert.',
      price: 125,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Cottage Cheese', 'Sugar', 'Cardamom', 'Rose Water'],
      preparationTime: 20,
      addOns: [
        { name: 'Extra Rasgulla (2 pcs)', price: 60, available: true },
        { name: 'Ice Cream', price: 50, available: true },
        { name: 'Extra Syrup', price: 20, available: true },
      ],
    },
    {
      name: 'Kulfi',
      description: 'Traditional Indian ice cream made with reduced milk, flavored with cardamom and pistachios. Served frozen.',
      price: 135,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Milk', 'Sugar', 'Cardamom', 'Pistachios', 'Almonds', 'Saffron'],
      preparationTime: 10,
      addOns: [
        { name: 'Extra Kulfi (1 pc)', price: 65, available: true },
        { name: 'Falooda', price: 40, available: true },
        { name: 'Extra Nuts', price: 30, available: true },
      ],
    },
    {
      name: 'Badam Halwa',
      description: 'Rich and creamy almond pudding cooked with ghee, sugar, and cardamom. A luxurious dessert.',
      price: 180,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Almonds', 'Ghee', 'Sugar', 'Milk', 'Cardamom', 'Saffron'],
      preparationTime: 25,
      addOns: [
        { name: 'Extra Almonds', price: 40, available: true },
        { name: 'Extra Ghee', price: 25, available: true },
        { name: 'Ice Cream', price: 50, available: true },
      ],
    },
    {
      name: 'Shahi Tukda',
      description: 'Bread pudding with rich, creamy rabri, garnished with nuts and saffron. A royal dessert.',
      price: 160,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Bread', 'Milk', 'Sugar', 'Ghee', 'Almonds', 'Pistachios', 'Saffron'],
      preparationTime: 20,
      addOns: [
        { name: 'Extra Rabri', price: 50, available: true },
        { name: 'Extra Nuts', price: 30, available: true },
        { name: 'Extra Saffron', price: 40, available: true },
      ],
    },
    {
      name: 'Moong Dal Halwa',
      description: 'Sweet lentil pudding cooked with ghee, sugar, and cardamom. A warm and comforting dessert.',
      price: 145,
      category: 'dessert',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Moong Dal', 'Ghee', 'Sugar', 'Milk', 'Cardamom', 'Almonds'],
      preparationTime: 30,
      addOns: [
        { name: 'Extra Nuts', price: 30, available: true },
        { name: 'Extra Ghee', price: 25, available: true },
        { name: 'Ice Cream', price: 50, available: true },
      ],
    },
  ],
  beverage: [
    {
      name: 'Mango Lassi',
      description: 'Creamy and refreshing yogurt drink blended with fresh mango pulp. A perfect cooling beverage.',
      price: 120,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Yogurt', 'Mango Pulp', 'Sugar', 'Cardamom', 'Ice'],
      preparationTime: 5,
      addOns: [
        { name: 'Extra Mango', price: 30, available: true },
        { name: 'Extra Thick', price: 20, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
    {
      name: 'Sweet Lassi',
      description: 'Traditional yogurt drink sweetened with sugar and flavored with cardamom. Cool and refreshing.',
      price: 100,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Yogurt', 'Sugar', 'Cardamom', 'Ice', 'Rose Water'],
      preparationTime: 5,
      addOns: [
        { name: 'Extra Thick', price: 20, available: true },
        { name: 'Extra Sweet', price: 10, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
    {
      name: 'Masala Chai',
      description: 'Aromatic Indian tea brewed with spices like cardamom, ginger, and cinnamon. Served hot.',
      price: 80,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Tea Leaves', 'Milk', 'Sugar', 'Cardamom', 'Ginger', 'Cinnamon'],
      preparationTime: 8,
      addOns: [
        { name: 'Extra Strong', price: 10, available: true },
        { name: 'Extra Spices', price: 15, available: true },
        { name: 'Extra Milk', price: 10, available: true },
      ],
    },
    {
      name: 'Fresh Lime Soda',
      description: 'Refreshing lime juice mixed with soda water and sugar. A perfect summer cooler.',
      price: 90,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Lime', 'Soda Water', 'Sugar', 'Salt', 'Ice', 'Mint'],
      preparationTime: 5,
      addOns: [
        { name: 'Extra Lime', price: 15, available: true },
        { name: 'Extra Sweet', price: 10, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
    {
      name: 'Buttermilk',
      description: 'Cool and refreshing spiced buttermilk, perfect for digestion. A traditional Indian drink.',
      price: 85,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Buttermilk', 'Salt', 'Cumin', 'Coriander', 'Ginger', 'Curry Leaves'],
      preparationTime: 5,
      addOns: [
        { name: 'Extra Spicy', price: 10, available: true },
        { name: 'Extra Thick', price: 15, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
    {
      name: 'Rose Sharbat',
      description: 'Sweet and fragrant rose-flavored drink, served chilled. A refreshing traditional beverage.',
      price: 95,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Rose Syrup', 'Water', 'Sugar', 'Lime', 'Ice', 'Mint'],
      preparationTime: 5,
      addOns: [
        { name: 'Extra Rose', price: 20, available: true },
        { name: 'Extra Sweet', price: 10, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
    {
      name: 'Badam Milk',
      description: 'Creamy almond milk sweetened with sugar and flavored with cardamom and saffron.',
      price: 140,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Almonds', 'Milk', 'Sugar', 'Cardamom', 'Saffron', 'Pistachios'],
      preparationTime: 10,
      addOns: [
        { name: 'Extra Almonds', price: 30, available: true },
        { name: 'Extra Saffron', price: 40, available: true },
        { name: 'Extra Thick', price: 20, available: true },
      ],
    },
    {
      name: 'Thandai',
      description: 'Traditional spiced milk drink with almonds, fennel, and rose petals. Served chilled.',
      price: 150,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Milk', 'Almonds', 'Fennel', 'Rose Petals', 'Sugar', 'Cardamom', 'Pepper'],
      preparationTime: 12,
      addOns: [
        { name: 'Extra Nuts', price: 30, available: true },
        { name: 'Extra Spices', price: 20, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
    {
      name: 'Jaljeera',
      description: 'Tangy and spicy cumin-flavored drink, perfect as an appetizer. A refreshing digestive drink.',
      price: 90,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Cumin', 'Mint', 'Lime', 'Black Salt', 'Sugar', 'Water', 'Ice'],
      preparationTime: 5,
      addOns: [
        { name: 'Extra Spicy', price: 10, available: true },
        { name: 'Extra Tangy', price: 10, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
    {
      name: 'Cold Coffee',
      description: 'Rich and creamy iced coffee blended with milk and sugar. A perfect pick-me-up drink.',
      price: 130,
      category: 'beverage',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Coffee', 'Milk', 'Sugar', 'Ice', 'Chocolate Syrup'],
      preparationTime: 8,
      addOns: [
        { name: 'Extra Strong', price: 15, available: true },
        { name: 'Extra Cream', price: 20, available: true },
        { name: 'Extra Ice', price: 10, available: true },
      ],
    },
  ],
  salad: [
    {
      name: 'Garden Fresh Salad',
      description: 'Crisp mixed greens with fresh vegetables, tossed in a light vinaigrette. A healthy and refreshing option.',
      price: 180,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Lettuce', 'Tomato', 'Cucumber', 'Carrots', 'Bell Peppers', 'Olive Oil', 'Vinegar'],
      preparationTime: 10,
      addOns: [
        { name: 'Extra Vegetables', price: 30, available: true },
        { name: 'Extra Dressing', price: 20, available: true },
        { name: 'Feta Cheese', price: 40, available: true },
      ],
    },
    {
      name: 'Caesar Salad',
      description: 'Classic Caesar salad with crisp romaine lettuce, croutons, and creamy Caesar dressing.',
      price: 220,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Romaine Lettuce', 'Croutons', 'Parmesan Cheese', 'Caesar Dressing', 'Lemon'],
      preparationTime: 12,
      addOns: [
        { name: 'Extra Cheese', price: 40, available: true },
        { name: 'Extra Croutons', price: 25, available: true },
        { name: 'Extra Dressing', price: 20, available: true },
      ],
    },
    {
      name: 'Fruit Salad',
      description: 'Fresh seasonal fruits mixed together, served chilled. A sweet and healthy dessert option.',
      price: 160,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Apple', 'Banana', 'Orange', 'Grapes', 'Pomegranate', 'Honey', 'Mint'],
      preparationTime: 8,
      addOns: [
        { name: 'Extra Fruits', price: 40, available: true },
        { name: 'Extra Honey', price: 20, available: true },
        { name: 'Ice Cream', price: 50, available: true },
      ],
    },
    {
      name: 'Kachumber Salad',
      description: 'Traditional Indian salad with chopped cucumber, tomato, and onion, seasoned with salt and lemon.',
      price: 120,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Cucumber', 'Tomato', 'Onion', 'Lemon', 'Salt', 'Coriander', 'Green Chilli'],
      preparationTime: 5,
      addOns: [
        { name: 'Extra Vegetables', price: 25, available: true },
        { name: 'Extra Spicy', price: 10, available: true },
        { name: 'Extra Lemon', price: 10, available: true },
      ],
    },
    {
      name: 'Greek Salad',
      description: 'Mediterranean salad with fresh vegetables, olives, and feta cheese, drizzled with olive oil.',
      price: 240,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Cucumber', 'Tomato', 'Olives', 'Feta Cheese', 'Onion', 'Olive Oil', 'Oregano'],
      preparationTime: 10,
      addOns: [
        { name: 'Extra Feta', price: 50, available: true },
        { name: 'Extra Olives', price: 30, available: true },
        { name: 'Extra Dressing', price: 20, available: true },
      ],
    },
    {
      name: 'Coleslaw',
      description: 'Crisp shredded cabbage and carrots in a creamy mayonnaise dressing. A classic side salad.',
      price: 140,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Cabbage', 'Carrots', 'Mayonnaise', 'Vinegar', 'Sugar', 'Salt', 'Pepper'],
      preparationTime: 8,
      addOns: [
        { name: 'Extra Vegetables', price: 25, available: true },
        { name: 'Extra Dressing', price: 20, available: true },
        { name: 'Extra Creamy', price: 15, available: true },
      ],
    },
    {
      name: 'Waldorf Salad',
      description: 'Classic salad with apples, celery, walnuts, and grapes in a creamy dressing.',
      price: 200,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Apple', 'Celery', 'Walnuts', 'Grapes', 'Mayonnaise', 'Lemon', 'Lettuce'],
      preparationTime: 12,
      addOns: [
        { name: 'Extra Nuts', price: 40, available: true },
        { name: 'Extra Fruits', price: 30, available: true },
        { name: 'Extra Dressing', price: 20, available: true },
      ],
    },
    {
      name: 'Spinach Salad',
      description: 'Fresh baby spinach with mushrooms, onions, and a warm vinaigrette dressing.',
      price: 190,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Baby Spinach', 'Mushrooms', 'Onion', 'Bacon Bits', 'Vinaigrette', 'Egg'],
      preparationTime: 10,
      addOns: [
        { name: 'Extra Spinach', price: 30, available: true },
        { name: 'Extra Mushrooms', price: 35, available: true },
        { name: 'Extra Dressing', price: 20, available: true },
      ],
    },
    {
      name: 'Quinoa Salad',
      description: 'Nutritious quinoa salad with vegetables, herbs, and a lemon vinaigrette. A protein-rich option.',
      price: 210,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Quinoa', 'Cucumber', 'Tomato', 'Bell Peppers', 'Lemon', 'Olive Oil', 'Herbs'],
      preparationTime: 15,
      addOns: [
        { name: 'Extra Quinoa', price: 40, available: true },
        { name: 'Extra Vegetables', price: 30, available: true },
        { name: 'Extra Dressing', price: 20, available: true },
      ],
    },
    {
      name: 'Raita',
      description: 'Cool and refreshing yogurt salad with cucumber, mint, and spices. A perfect accompaniment to spicy dishes.',
      price: 100,
      category: 'salad',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Yogurt', 'Cucumber', 'Mint', 'Cumin', 'Salt', 'Coriander', 'Green Chilli'],
      preparationTime: 8,
      addOns: [
        { name: 'Extra Cucumber', price: 20, available: true },
        { name: 'Extra Spicy', price: 10, available: true },
        { name: 'Extra Mint', price: 15, available: true },
      ],
    },
  ],
  soup: [
    {
      name: 'Tomato Soup',
      description: 'Creamy and comforting tomato soup, served hot with croutons. A classic favorite.',
      price: 150,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Tomatoes', 'Onion', 'Garlic', 'Cream', 'Basil', 'Salt', 'Pepper'],
      preparationTime: 15,
      addOns: [
        { name: 'Extra Cream', price: 25, available: true },
        { name: 'Extra Croutons', price: 20, available: true },
        { name: 'Extra Spicy', price: 15, available: true },
      ],
    },
    {
      name: 'Hot & Sour Soup',
      description: 'Spicy and tangy soup with vegetables, tofu, and aromatic spices. An Indo-Chinese favorite.',
      price: 170,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Vegetables', 'Tofu', 'Vinegar', 'Soy Sauce', 'Ginger', 'Garlic', 'Chilli'],
      preparationTime: 12,
      addOns: [
        { name: 'Extra Spicy', price: 15, available: true },
        { name: 'Extra Vegetables', price: 30, available: true },
        { name: 'Extra Tofu', price: 35, available: true },
      ],
    },
    {
      name: 'Dal Soup',
      description: 'Comforting lentil soup with spices and herbs. A healthy and nutritious option.',
      price: 140,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Lentils', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Spices', 'Coriander'],
      preparationTime: 20,
      addOns: [
        { name: 'Extra Spicy', price: 15, available: true },
        { name: 'Extra Thick', price: 20, available: true },
        { name: 'Extra Lemon', price: 10, available: true },
      ],
    },
    {
      name: 'Corn Soup',
      description: 'Creamy sweet corn soup with vegetables, served hot. A comforting and delicious option.',
      price: 160,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Sweet Corn', 'Vegetables', 'Cream', 'Onion', 'Garlic', 'Pepper', 'Salt'],
      preparationTime: 15,
      addOns: [
        { name: 'Extra Corn', price: 30, available: true },
        { name: 'Extra Cream', price: 25, available: true },
        { name: 'Extra Vegetables', price: 25, available: true },
      ],
    },
    {
      name: 'Manchow Soup',
      description: 'Spicy and flavorful Indo-Chinese soup with vegetables and crispy noodles. A popular choice.',
      price: 180,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Vegetables', 'Noodles', 'Soy Sauce', 'Vinegar', 'Ginger', 'Garlic', 'Chilli'],
      preparationTime: 12,
      addOns: [
        { name: 'Extra Spicy', price: 15, available: true },
        { name: 'Extra Noodles', price: 25, available: true },
        { name: 'Extra Vegetables', price: 30, available: true },
      ],
    },
    {
      name: 'Mushroom Soup',
      description: 'Rich and creamy mushroom soup with fresh mushrooms and herbs. A hearty and comforting option.',
      price: 190,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Mushrooms', 'Onion', 'Garlic', 'Cream', 'Butter', 'Herbs', 'Pepper'],
      preparationTime: 15,
      addOns: [
        { name: 'Extra Mushrooms', price: 40, available: true },
        { name: 'Extra Cream', price: 25, available: true },
        { name: 'Extra Herbs', price: 20, available: true },
      ],
    },
    {
      name: 'Chicken Soup',
      description: 'Hearty chicken soup with vegetables and aromatic spices. A comforting and nourishing option.',
      price: 200,
      category: 'soup',
      isVeg: false,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Chicken', 'Vegetables', 'Ginger', 'Garlic', 'Spices', 'Coriander', 'Lemon'],
      preparationTime: 25,
      addOns: [
        { name: 'Extra Chicken', price: 60, available: true },
        { name: 'Extra Spicy', price: 15, available: true },
        { name: 'Extra Vegetables', price: 30, available: true },
      ],
    },
    {
      name: 'Vegetable Clear Soup',
      description: 'Light and clear vegetable soup with fresh vegetables and herbs. A healthy and refreshing option.',
      price: 130,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Mixed Vegetables', 'Ginger', 'Garlic', 'Herbs', 'Pepper', 'Salt', 'Lemon'],
      preparationTime: 12,
      addOns: [
        { name: 'Extra Vegetables', price: 30, available: true },
        { name: 'Extra Spicy', price: 15, available: true },
        { name: 'Extra Herbs', price: 20, available: true },
      ],
    },
    {
      name: 'Lemon Coriander Soup',
      description: 'Tangy and refreshing soup with lemon, coriander, and vegetables. A perfect appetizer.',
      price: 145,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Vegetables', 'Lemon', 'Coriander', 'Ginger', 'Garlic', 'Pepper', 'Salt'],
      preparationTime: 10,
      addOns: [
        { name: 'Extra Lemon', price: 10, available: true },
        { name: 'Extra Coriander', price: 15, available: true },
        { name: 'Extra Spicy', price: 15, available: true },
      ],
    },
    {
      name: 'Cream of Broccoli Soup',
      description: 'Creamy and smooth broccoli soup with herbs and spices. A nutritious and delicious option.',
      price: 175,
      category: 'soup',
      isVeg: true,
      available: true,
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
      ingredients: ['Broccoli', 'Onion', 'Garlic', 'Cream', 'Butter', 'Herbs', 'Pepper'],
      preparationTime: 18,
      addOns: [
        { name: 'Extra Broccoli', price: 35, available: true },
        { name: 'Extra Cream', price: 25, available: true },
        { name: 'Extra Herbs', price: 20, available: true },
      ],
    },
  ],
};

async function addAllMenuItems() {
  try {
    await connectDB();
    console.log('📦 Connected to database\n');

    let totalAdded = 0;
    let totalSkipped = 0;

    for (const [category, items] of Object.entries(menuItems)) {
      console.log(`\n📋 Processing ${category.toUpperCase()} category...`);
      let added = 0;
      let skipped = 0;

      for (const item of items) {
        // Check if item already exists
        const existing = await Menu.findOne({ name: item.name, category: category });
        
        if (existing) {
          console.log(`  ⏭️  Skipped: ${item.name} (already exists)`);
          skipped++;
          totalSkipped++;
          continue;
        }

        const menuItem = new Menu(item);
        await menuItem.save();
        console.log(`  ✅ Added: ${item.name} - ₹${item.price}`);
        added++;
        totalAdded++;
      }

      console.log(`  ✅ ${category}: Added ${added}, Skipped ${skipped}`);
    }

    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`✅ Successfully added ${totalAdded} menu items`);
    console.log(`⏭️  Skipped ${totalSkipped} items (already exist)`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    // Show summary by category
    console.log('📊 Summary by Category:');
    for (const category of Object.keys(menuItems)) {
      const count = await Menu.countDocuments({ category, available: true });
      console.log(`  ${category.charAt(0).toUpperCase() + category.slice(1)}: ${count} items`);
    }

    process.exit(0);
  } catch (error: any) {
    console.error('❌ Error adding menu items:', error.message);
    process.exit(1);
  }
}

addAllMenuItems();

